# Generated by Django 2.0.3 on 2018-03-20 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PurpleCat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='upload_time2',
            new_name='upload_time',
        ),
    ]
