# Generated by Django 2.0.3 on 2018-03-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurpleCat', '0002_auto_20180320_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='Title'),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='upload_time',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(blank=True),
        ),
    ]
