# Generated by Django 2.0.3 on 2018-03-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurpleCat', '0003_auto_20180321_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
