# Generated by Django 2.0.3 on 2018-03-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurpleCat', '0007_auto_20180324_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(blank=True, default='C:\\Users\\Ihor\\PycharmProjects\\PurpleCat\\media/uploads/', max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\Ihor\\PycharmProjects\\PurpleCat\\media/uploads/'),
        ),
    ]
