# Generated by Django 2.0.3 on 2018-03-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurpleCat', '0009_auto_20180324_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='PurpleCat/media/uploads/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(blank=True, default='PurpleCat/media/uploads/', max_length=256),
        ),
    ]
